.PHONY: all
all: sixtyfour

.PHONY: sixtyfour
sixtyfour: config.yaml production/Sixtyfour.glyphs fonts/variable/Sixtyfour[BLED,SCAN].ttf

fonts/variable/Sixtyfour[BLED,SCAN].ttf:
	gftools builder config.yaml
