sources:
  - production/Workbench.glyphs
axisOrder:
  - SCAN
  - BLED
familyName: Workbench
buildOTF: false
buildTTF: false
outputDir: fonts
autohintTTF: false
flattenComponents: false
stat:
  WorkbenchC[BLED,SCAN].ttf:
  - name: Scanlines
    tag: SCAN
    values:
    - name: Regular
      value: 100
  - name: Bleed
    tag: BLED
    values:
    - name: Regular
      value: 0
      flags: 2
